# Generated by Django 3.0.8 on 2020-07-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_plans_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='image',
            field=models.ImageField(default='image', upload_to='images'),
        ),
    ]
