# Generated by Django 3.0.8 on 2020-07-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='email', max_length=254),
        ),
    ]
